<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
		<?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

		<?php
		echo $this->headMeta()
				->appendName('viewport', 'width=device-width, initial-scale=1.0')
				->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

        <!-- Le styles -->
		<?php
		echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
				->prependStylesheet($this->basePath() . '/css/style.css')
				->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
//				->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
				->prependStylesheet($this->basePath() . '/css/bootstrap.min_1.css')
		?>

        <!-- Scripts -->
		<?php
		echo $this->headScript()
				->prependFile($this->basePath() . '/js/bootstrap.min.js')
				->prependFile($this->basePath() . '/js/jquery.min.js')
				->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
				->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
		;
		?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('SeekJobs') ?></a>
                </div>
				<div>
					<ul class="nav navbar-nav navbar-left">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Entreprises<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="#">Mon compte</a></li>
								<li class="divider"></li>
								<li class="dropdown-header">Mes offres</li>
								<li><a href="http://seekjobs.dev/offres/ajouter">Ajouter une offre</a></li>
								<li><a href="http://seekjobs.dev/offres/modifier/1">Modifier une offre</a></li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Candidats<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="http://seekjobs.dev/offres/inscription">Mon compte</a></li>
								<li class="divider"></li>
								<li class="dropdown-header">Mes candidatures</li>
								<li><a href="#">Voir l'états des mes candidatures</a></li>
							</ul>
						</li>
						<li><a href="http://seekjobs.dev/offres/inscription">Créer mon compte</a></li>
					</ul>
				</div><!--/.nav-collapse -->
				<form class="navbar-form navbar-right" role="form">
					<div class="form-group">
						<input type="text" placeholder="Email" class="form-control">
					</div>
					<div class="form-group">
						<input type="password" placeholder="Password" class="form-control">
					</div>
					<button type="submit" class="btn btn-success">Sign in</button>
				</form>
            </div>
        </nav>

        <div class="container">
			<?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
		<?php echo $this->inlineScript() ?>
    </body>
</html>
