<?php // var_dump($_POST);  ?>
<div>
	<ul class="pager">
		<li class="previous"><a href="http://seekjobs.dev">&larr; Retourner à la liste d'offres</a></li>
		<?php // <li class="next"><a href="#">Voir l'offre suivante &rarr;</a></li>  ?>
	</ul>
</div>

<!--offre exemple-->
<div class="panel panel-default offre">
	<div class="panel-heading clearfix">
		<h3 class="panel-title"><span class="pull-left">
				<a href="http://seekjobs.dev/offres/detail/<?php echo $offre->getId(); ?>"><?php echo $offre->getTitre(); ?></a></span> 
			<strong class="pull-right"><a href="#"><?php echo $offre->getType(); ?></a></strong></h3></div>
	<div class="panel-body">
		<p class="clearfix">
			<span class="pull-left">
				<strong><a href="#"><?php echo $offre->getDenomination(); ?></a></strong> à <?php echo $offre->getVille(); ?></span>  
			<span class="pull-right">Offre publié <?php echo $offre->getDate_creation(); ?> <a href="#postCadidature" class="btn btn-link"> <span class="glyphicon glyphicon-thumbs-up"></span> POSTULER </a></span>
		</p>
		<h4>Description :</h4>
		<p><?php echo $offre->getDescription(); ?></p>
		<p>
			<?php //TODO cahnger la couleur des liens car la c'est affreux ' ?>
			<?php foreach ($offre->getTabCompetences() as $tag) : ?>
				<span class="badge pad"><a href="../offres/searchBy/tag/<?php echo $tag->getId(); ?>"><?php echo $tag->getTitre(); ?></a></span>
			<?php endforeach; ?>
		</p>
	</div>
</div>
<!--offre exemple-->

<div class="panel panel-default">
	<div class="panel-heading clearfix"><h4>Repondre à cette offre :</h4></div>
	<?php
	//TODO PENSER A PRE REMPLIR LES CHAMPS SI CONNECTe 
	//TODO OPTION Validation de formulaire (champs prenom, nom, email, cv obligatoires, CV de type PDF, Word ou ODT et ne dépassant pas 1Mo, email au format valide) 
	?>
	<div class="panel-body">
		<div class="alert alert-success alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<strong>Super !</strong> Votre candidature à été soumis correctement
		</div>

		<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<strong>Oups !</strong> Votre Un erreur est survenu merci de soumettre à nouveau votre candidature
		</div>
			<form role="form" id="postCadidature" method="POST"  action="" enctype="multipart/form-data">
			<input type="hidden" name="user_id"  value="<?php echo $userID; ?>"  />
			<input type="hidden" name="offre_id"  value="<?php echo $offre_id; ?>"  />
			<div class="form-group">
				<label for="nom">Nom</label>
				<input type="text" class="form-control" id="nom" placeholder="Votre nom" name="nom">
			</div>
			<div class="form-group">
				<label for="prenom">Prénom</label>
				<input type="text" class="form-control" id="prenom" placeholder="Votre Prénom" name="prenom">
			</div>
			<div class="form-group">
				<label for="email">Email</label>
				<input type="email" class="form-control" id="email" placeholder="Votre email" name="mail">
			</div>
			<div class="form-group">
				<label for="message">Votre message :</label>
				<textarea class="form-control" id="message" placeholder="Votre message" name="message_motivation"></textarea>
			</div>
			<div class="form-group">
				<label for="cv">Envoyer votre CV</label>
				<input type="file" id="cv" name="cv">
				<p class="help-block">Formats .pdf, .odt, .doc, poids max 10M</p>
			</div>
			<button type="submit" class="btn btn-default">Repondre</button>
		</form>
	</div>
</div>
<div>
	<ul class="pager">
		<li class="previous"><a href="http://seekjobs.dev">&larr; Retourner à la liste d'offres</a></li>
		<li class="next"><a href="#">Voir l'offre suivante &rarr;</a></li>
	</ul>
</div>
