<?php var_dump($_POST); ?>
<div class="panel panel-default">
	<div class="panel-heading clearfix"><h4>Créer mon compte</h4></div>
	<?php
	//TODO PENSER A PRE REMPLIR LES CHAMPS SI CONNECTe 
	//TODO OPTION Validation de formulaire (champs prenom, nom, email, cv obligatoires, CV de type PDF, Word ou ODT et ne dépassant pas 1Mo, email au format valide) 
	?>
	<div class="panel-body">
		<div class="alert alert-success alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<strong>Super !</strong> Votre compte a été crée !
		</div>

		<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<strong>Oups !</strong>Un erreur est survenu merci votre comprehension
		</div>

		<!--FORM-->
		<div class="row show-grid">
			<div class="col-md-8">
				<div class="panel-body">
					<form role="form" action="" method="post">
						<div class="row">
							<div class=" col-lg-6">
								<div class="form-group">
									<label for="nom">Nom</label>
									<input type="text" class="form-control" id="nom" placeholder="Votre nom" name="nom">
								</div>
							</div>
							<div class=" col-lg-6">
								<div class="form-group">
									<label for="prenom">Prénom</label>
									<input type="text" class="form-control" id="prenom" placeholder="Votre Prénom" name="prenom">
								</div>
							</div>
						</div>

						<div class="row">
							<div class=" col-lg-6">
								<div class="form-group">
									<label for="email">Email</label>
									<input type="email" class="form-control" id="email" placeholder="Votre email" name="email">
								</div>
							</div>

							<div class=" col-lg-6">
								<div class="form-group">
									<label for="tel">Telephone</label>
									<input type="tel" class="form-control" id="tel" placeholder="00-00-00-00-00-00" name="tel">
								</div>
							</div>
						</div>

						<div class="form-group">
							<label for="cv">Envoyer votre CV</label>
							<input type="file" id="cv" name="cv">
							<p class="help-block">Formats .pdf, .odt, .doc, poids max 10M</p>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<div class="form-group">
									<label for="denomination">Nom de votre société</label>
									<input type="text" class="form-control" id="denomination" placeholder="Nom de votre societé" name="denomination">
								</div>
							</div>
						</div>
						&nbsp;
						<div class="row">
							<div class=" col-lg-6">
								<label for="cp">Code postale</label>
								<input type="text" class="form-control" id="cp" placeholder="Code postale">
							</div>

							<div class=" col-lg-6">
								<label for="ville">Ville</label>
								<input type="text" class="form-control" id="ville" placeholder="Ville">
							</div>
						</div>
						&nbsp;
						<div class="row">
							<div class="row">
								<div class="panel-body">
									<input type="submit" class="btn btn-success btn-lg btn-block" value="ENREGISTRER"/>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
		<!--FORM-->
	</div>
</div>