
<div class="panel panel-default">
	<div class="panel-heading clearfix"><h4>Modifier votre offre :</h4></div>
	<?php
	//TODO 
	//TODO 
	?>
	<div class="panel-body">

		<div class="alert alert-success alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<strong>Super !</strong> Votre candidature à été soumis correctement
		</div>

		<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<strong>Oups !</strong> Votre Un erreur est survenu merci de soumettre à nouveau votre candidature
		</div>

		<div class="row show-grid">
			<div class="col-md-8">
				<div class="panel-body">
					<form role="form">
						<div class="row">
							<div class="col-lg-12">
								<label for="titre">Titre</label>
								<input type="text" class="form-control" id="nom" placeholder="Titre de votre offre">
							</div>
						</div>
						&nbsp;
						<div class="row">
							<div class="col-lg-12">
								<div class="form-group">
									<label for="denomination">Nom de votre société</label>
									<input type="text" class="form-control" id="denomination" placeholder="Nom de votre societé">
								</div>
							</div>
							<div class="col-lg-12"> 
								<label for="type">Type de l'offre</label><br />
								<select class="form-control" name="type">
									<option>Stage</option>
									<option>Alternance</option>
									<option>CDD</option>
									<option>CDI</option>
								</select>
							</div>
						</div>
						&nbsp;
						<div class="row">
							<div class=" col-lg-6">
								<label for="cp">Code postale</label>
								<input type="text" class="form-control" id="cp" placeholder="Code postale">
							</div>

							<div class=" col-lg-6">
								<label for="ville">Ville</label>
								<input type="text" class="form-control" id="ville" placeholder="Ville">
							</div>
						</div>
						&nbsp;
						<div class="row">
							<div class="form-group col-lg-12">
								<label for="message">Description de votre offre :</label>
								<textarea class="form-control" rows="3" id="message" placeholder="Description de l'offre"></textarea>
								<p class="help-block text-center"><span>Maximun 1000 caracteres</span> -- <strong><span class="text-danger">50</span>/1000</strong></p>
							</div>
						</div>
						&nbsp;
						<div class="row">
							<div class="row">
								<div class="panel-body">
									<button type="button" class="btn btn-success btn-lg btn-block">ENREGISTRER</button>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
			<div id="competences">
				<style>.pad{
						padding: 10px;
						margin: 5px 5px;
						display:inline-block;
						/*min-width: 25%;*/
						/*max-width: 50%;*/
					}
					#competences a{ color:white;}
					#inputAddComptence{
						text-align: center;
					}
				</style>
				<div class="col-md-4" id="inputAddComptence">
					<form class="navbar-form" role="form">
						<div class="form-group">
							<input type="tag"  placeholder="exemple PHP" class="form-control">
						</div>
						<button type="submit" class="btn btn-success">Ajouter</button>
					</form>
				</div>
				<div>
					<span class="badge pad"><a href="#">PHP <span class="glyphicon glyphicon-remove"></span></a></span>
					<span class="badge pad"><a href="#">java <span class="glyphicon glyphicon-remove"></span></a></span>
					<span class="badge pad"><a href="#">css <span class="glyphicon glyphicon-remove"></span></a></span>
					<span class="badge pad"><a href="#">html <span class="glyphicon glyphicon-remove"></span></a></span>
					<span class="badge pad"><a href="#">Java <span class="glyphicon glyphicon-remove"></span> </a></span>	
				</div>
			</div>
		</div>
    </div>
</div>
<div>
	<ul class="pager">
		<li class="previous disabled"><a href="#">&larr; Retourner à la liste d'offres</a></li>
		<li class="next"><a href="#">Voir l'offre suivante &rarr;</a></li>
	</ul>
</div>
